language: cpp

sudo: true

dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-7
    packages:
      - g++-6
      - gcc-6

before_install:
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 90
- sudo apt-get install -y equivs openjdk-8-jdk
- wget -O buck.deb https://github.com/facebook/buck/releases/download/v2018.08.27.01/buck.2018.08.27.01_all.deb
- sudo dpkg -i buck.deb
- buck --version
- wget -O buckaroo.deb https://github.com/LoopPerfect/buckaroo/releases/download/v1.4.1/buckaroo.deb
- sudo dpkg -i buckaroo.deb
- buckaroo version
- c++ --version
- clang++ --version
- g++ --version
- gcc --version

script:
- buck build :support -c ui.superconsole=DISABLED
- buck build :ir -c ui.superconsole=DISABLED
- buck build :analysis -c ui.superconsole=DISABLED
- buck build :transforms -c ui.superconsole=DISABLED
- buck build :executionengine -c ui.superconsole=DISABLED
- buck build :llvm -c ui.superconsole=DISABLED
- buck run examples/Fibonacci
