cxx_binary(
  name = 'ParallelJIT', 
  srcs = [
    'ParallelJIT.cpp', 
  ], 
  compiler_flags = [
    '-pthread', 
  ], 
  deps = [
    # '//:llvm', 
    '//:support', 
    '//:executionengine', 
    '//:mcjit', 
    '//:mc', 
    '//:x86', 
    '//:pthread', 
  ], 
)
